#oracle
CREATE TABLE userUpload (
    seq NUMBER(10) PRIMARY KEY,
    imageName VARCHAR2(50),
    imageContent VARCHAR2(4000),
    imageFileName VARCHAR2(100) NOT NULL,
    imageOriginalFileName VARCHAR2(100) NOT NULL
);

CREATE sequence SEQ_USERIMAGE nocycle nocache

#MYSQL
CREATE TABLE userUpload (
    seq INT(10) PRIMARY KEY AUTO_INCREMENT,
    imageName VARCHAR(50),
    imageContent VARCHAR(4000),
    imageFileName VARCHAR(100) NOT NULL,
    imageOriginalFileName VARCHAR(100) NOT NULL
);

CREATE TABLE userUpload (
    seq NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imageName VARCHAR2(50),
    imageContent VARCHAR2(4000),
    imageFileName VARCHAR2(100) NOT NULL,
    imageOriginalFileName VARCHAR2(100) NOT NULL
);